const mongoose = require('mongoose');
const { connectMongo } = require('./src/config/mongo');
const Category = require('./src/modules/categories/category.model');
const Product = require('./src/modules/products/product.model');
const User = require('./src/modules/auth/auth.model');

async function seedDatabase() {
  try {
    await connectMongo();

    // Limpiar datos existentes
    await Category.deleteMany({});
    await Product.deleteMany({});
    await User.deleteMany({});

    // Crear categorías
    const categories = await Category.insertMany([
      { name: 'Procesadores', slug: 'procesadores' },
      { name: 'Tarjetas Madre', slug: 'tarjetas-madre' },
      { name: 'Memoria RAM', slug: 'memoria-ram' },
      { name: 'Tarjetas de Video', slug: 'tarjetas-video' },
      { name: 'Almacenamiento', slug: 'almacenamiento' },
      { name: 'Fuentes de Poder', slug: 'fuentes-poder' },
      { name: 'Gabinetes', slug: 'gabinetes' },
      { name: 'Refrigeración', slug: 'refrigeracion' },
    ]);

    console.log('✅ Categorías creadas:', categories.length);

    // Crear productos de ejemplo
    const products = await Product.insertMany([
      {
        externalId: 'intel-i5-12400f',
        title: 'Procesador Intel Core i5-12400F',
        description: 'Procesador de 6 núcleos para gaming y trabajo diario.',
        provider: 'amazon',
        image: 'https://via.placeholder.com/400x300.png?text=Intel+i5',
        price: 154.99,
        originalPrice: 199.99,
        discount: 23,
        rating: 4.6,
        stock: 50,
        available: true,
        url: 'https://amazon.example.com/product/intel-i5-12400f',
        category: 'procesadores',
        specs: { cores: 6, threads: 12, baseClock: '2.5GHz', boostClock: '4.4GHz' },
      },
      {
        externalId: 'asus-tuf-b650',
        title: 'Tarjeta Madre ASUS TUF GAMING B650',
        description: 'Tarjeta madre AM5 preparada para gaming y overclocking.',
        provider: 'mercadolibre',
        image: 'https://via.placeholder.com/400x300.png?text=ASUS+TUF',
        price: 229.0,
        rating: 4.5,
        stock: 30,
        available: true,
        url: 'https://mercadolibre.example.com/product/asus-tuf-b650',
        category: 'tarjetas-madre',
        specs: { socket: 'AM5', chipset: 'B650', ramSupport: 'DDR5', formFactor: 'ATX' },
      },
      {
        externalId: 'corsair-vengeance-16gb',
        title: 'Memoria RAM Corsair Vengeance 16GB DDR4',
        description: 'Memoria RAM rápida para gaming y trabajo profesional.',
        provider: 'cyberpuerta',
        image: 'https://via.placeholder.com/400x300.png?text=Corsair+RAM',
        price: 47.99,
        originalPrice: 69.99,
        discount: 31,
        rating: 4.7,
        stock: 100,
        available: true,
        url: 'https://cyberpuerta.example.com/product/corsair-vengeance-16gb',
        category: 'memoria-ram',
        specs: { capacity: '16GB', type: 'DDR4', speed: '3200MHz', latency: 'CL16' },
      },
      {
        externalId: 'rtx-4060-gaming',
        title: 'Tarjeta de Video RTX 4060 Gaming',
        description: 'Potente tarjeta gráfica para juegos y edición.',
        provider: 'ddtech',
        image: 'https://via.placeholder.com/400x300.png?text=RTX+4060',
        price: 299.90,
        originalPrice: 349.90,
        discount: 14,
        rating: 4.6,
        stock: 20,
        available: true,
        url: 'https://ddtech.example.com/product/rtx-4060-gaming',
        category: 'tarjetas-video',
        specs: { chipset: 'NVIDIA RTX 4060', memory: '8GB', type: 'GDDR6', interface: 'PCIe 4.0' },
      },
      {
        externalId: 'ssd-samsung-1tb',
        title: 'SSD Samsung 980 PRO 1TB NVMe',
        description: 'Almacenamiento ultrarrápido para sistemas y juegos.',
        provider: 'amazon',
        image: 'https://via.placeholder.com/400x300.png?text=Samsung+SSD',
        price: 84.99,
        originalPrice: 119.95,
        discount: 29,
        rating: 4.8,
        stock: 75,
        available: true,
        url: 'https://amazon.example.com/product/samsung-980-pro-1tb',
        category: 'almacenamiento',
        specs: { capacity: '1TB', interface: 'NVMe PCIe 4.0', readSpeed: '7000MB/s', writeSpeed: '5100MB/s' },
      },
      {
        externalId: 'asus-tuf-gaming-laptop',
        title: 'Laptop ASUS TUF Gaming 15.6"',
        description: 'Portátil gamer con procesador Intel y gráfica dedicada.',
        provider: 'amazon',
        image: 'https://via.placeholder.com/400x300.png?text=ASUS+Laptop',
        price: 1299.99,
        rating: 4.4,
        stock: 18,
        available: true,
        url: 'https://amazon.example.com/product/asus-tuf-gaming-laptop',
        category: 'laptops',
        specs: { cpu: 'Intel Core i7', gpu: 'RTX 4050', ram: '16GB', storage: '1TB SSD' },
      },
      {
        externalId: 'acer-nitro-5',
        title: 'Laptop Acer Nitro 5 15.6"',
        description: 'Laptop gamer económica con refrigeración avanzada.',
        provider: 'mercadolibre',
        image: 'https://via.placeholder.com/400x300.png?text=Acer+Nitro',
        price: 1149.0,
        rating: 4.2,
        stock: 22,
        available: true,
        url: 'https://mercadolibre.example.com/product/acer-nitro-5',
        category: 'laptops',
        specs: { cpu: 'Intel Core i5', gpu: 'RTX 3050', ram: '8GB', storage: '512GB SSD' },
      },
      {
        externalId: 'hyperx-alloy',
        title: 'Teclado Mecánico HyperX Alloy FPS',
        description: 'Teclado mecánico compacto con switches rojos.',
        provider: 'cyberpuerta',
        image: 'https://via.placeholder.com/400x300.png?text=HyperX+Alloy',
        price: 64.90,
        originalPrice: 99.90,
        discount: 35,
        rating: 4.5,
        stock: 45,
        available: true,
        url: 'https://cyberpuerta.example.com/product/hyperx-alloy',
        category: 'teclados',
        specs: { layout: 'TKL', switch: 'Red', rgb: true },
      },
      {
        externalId: 'logitech-g502',
        title: 'Mouse Logitech G502 HERO',
        description: 'Mouse gamer con sensor HERO 25K y pesas ajustables.',
        provider: 'amazon',
        image: 'https://via.placeholder.com/400x300.png?text=Logitech+G502',
        price: 44.99,
        originalPrice: 69.00,
        discount: 35,
        rating: 4.7,
        stock: 85,
        available: true,
        url: 'https://amazon.example.com/product/logitech-g502',
        category: 'mouse',
        specs: { dpi: '25600', botones: 11, rgb: true },
      },
      {
        externalId: 'samsung-odyssey-g5',
        title: 'Monitor Samsung Odyssey G5 27"',
        description: 'Monitor curvo 144Hz para gaming fluido.',
        provider: 'mercadolibre',
        image: 'https://via.placeholder.com/400x300.png?text=Odyssey+G5',
        price: 249.99,
        originalPrice: 329.99,
        discount: 24,
        rating: 4.6,
        stock: 16,
        available: true,
        url: 'https://mercadolibre.example.com/product/samsung-odyssey-g5',
        category: 'monitores',
        specs: { refreshRate: '144Hz', resolution: '2560x1440', curve: '1000R' },
      },
      {
        externalId: 'steelseries-arctis-7',
        title: 'Auriculares SteelSeries Arctis 7',
        description: 'Audífonos inalámbricos con sonido surround.',
        provider: 'ddtech',
        image: 'https://via.placeholder.com/400x300.png?text=Arctis+7',
        price: 149.99,
        rating: 4.5,
        stock: 40,
        available: true,
        url: 'https://ddtech.example.com/product/steelseries-arctis-7',
        category: 'audífonos',
        specs: { wireless: true, battery: '24h', mic: true },
      },
      {
        externalId: 'corsair-rm750x',
        title: 'Fuente Corsair RM750x 750W',
        description: 'Fuente modular con certificación 80 Plus Gold.',
        provider: 'amazon',
        image: 'https://via.placeholder.com/400x300.png?text=RM750x',
        price: 129.99,
        rating: 4.8,
        stock: 33,
        available: true,
        url: 'https://amazon.example.com/product/corsair-rm750x',
        category: 'fuentes-poder',
        specs: { wattage: '750W', modular: true, efficiency: '80+ Gold' },
      },
      {
        externalId: 'nzxt-h510',
        title: 'Gabinete NZXT H510',
        description: 'Gabinete ATX con diseño minimalista y buen flujo de aire.',
        provider: 'mercadolibre',
        image: 'https://via.placeholder.com/400x300.png?text=NZXT+H510',
        price: 99.5,
        rating: 4.4,
        stock: 25,
        available: true,
        url: 'https://mercadolibre.example.com/product/nzxt-h510',
        category: 'gabinetes',
        specs: { formFactor: 'ATX', usb: 'USB-C', color: 'negro' },
      },
      {
        externalId: 'noctua-nh-d15',
        title: 'Cooler Noctua NH-D15',
        description: 'Disipador de aire de alto rendimiento para CPU.',
        provider: 'cyberpuerta',
        image: 'https://via.placeholder.com/400x300.png?text=Noctua+NH-D15',
        price: 99.99,
        rating: 4.9,
        stock: 12,
        available: true,
        url: 'https://cyberpuerta.example.com/product/noctua-nh-d15',
        category: 'refrigeracion',
        specs: { type: 'aire', fans: 2, noise: '24dBA' },
      },
      {
        externalId: 'wd-black-2tb',
        title: 'SSD Western Digital Black 2TB NVMe',
        description: 'SSD de alto rendimiento para gaming y edición.',
        provider: 'amazon',
        image: 'https://via.placeholder.com/400x300.png?text=WD+Black',
        price: 179.99,
        rating: 4.7,
        stock: 50,
        available: true,
        url: 'https://amazon.example.com/product/wd-black-2tb',
        category: 'almacenamiento',
        specs: { capacity: '2TB', interface: 'NVMe PCIe 4.0', readSpeed: '7300MB/s' },
      },
      {
        externalId: 'seagate-barracuda-4tb',
        title: 'HDD Seagate Barracuda 4TB',
        description: 'Disco duro confiable para almacenamiento masivo.',
        provider: 'mercadolibre',
        image: 'https://via.placeholder.com/400x300.png?text=Seagate+4TB',
        price: 89.99,
        rating: 4.3,
        stock: 60,
        available: true,
        url: 'https://mercadolibre.example.com/product/seagate-barracuda-4tb',
        category: 'almacenamiento',
        specs: { capacity: '4TB', rpm: '7200', cache: '256MB' },
      },
      {
        externalId: 'gskill-tridentz-32gb',
        title: 'Memoria RAM G.Skill Trident Z 32GB DDR4',
        description: 'Kit de memoria para entusiastas y overclockers.',
        provider: 'ddtech',
        image: 'https://via.placeholder.com/400x300.png?text=Trident+Z',
        price: 159.0,
        rating: 4.8,
        stock: 40,
        available: true,
        url: 'https://ddtech.example.com/product/gskill-tridentz-32gb',
        category: 'memoria-ram',
        specs: { capacity: '32GB', type: 'DDR4', speed: '3600MHz' },
      },
      {
        externalId: 'msi-z690',
        title: 'Motherboard MSI MPG Z690',
        description: 'Tarjeta madre para procesadores Intel de última generación.',
        provider: 'amazon',
        image: 'https://via.placeholder.com/400x300.png?text=MSI+Z690',
        price: 249.99,
        rating: 4.5,
        stock: 28,
        available: true,
        url: 'https://amazon.example.com/product/msi-z690',
        category: 'tarjetas-madre',
        specs: { socket: 'LGA1700', chipset: 'Z690', ramSupport: 'DDR5' },
      },
      {
        externalId: 'radeon-rx-6700xt',
        title: 'Tarjeta de Video Radeon RX 6700 XT',
        description: 'GPU para gaming 1440p de alto rendimiento.',
        provider: 'mercadolibre',
        image: 'https://via.placeholder.com/400x300.png?text=RX+6700+XT',
        price: 379.99,
        rating: 4.4,
        stock: 18,
        available: true,
        url: 'https://mercadolibre.example.com/product/radeon-rx-6700xt',
        category: 'tarjetas-video',
        specs: { memory: '12GB', type: 'GDDR6', interface: 'PCIe 4.0' },
      },
      {
        externalId: 'evga-650-g5',
        title: 'Fuente EVGA SuperNOVA 650 G5',
        description: 'Fuente compacta y totalmente modular con 80 Plus Gold.',
        provider: 'cyberpuerta',
        image: 'https://via.placeholder.com/400x300.png?text=EVGA+650+G5',
        price: 109.99,
        rating: 4.7,
        stock: 35,
        available: true,
        url: 'https://cyberpuerta.example.com/product/evga-650-g5',
        category: 'fuentes-poder',
        specs: { wattage: '650W', modular: true, efficiency: '80+ Gold' },
      },
      {
        externalId: 'lg-ultragear-27',
        title: 'Monitor LG UltraGear 27" 144Hz',
        description: 'Monitor para gaming con colores vivos y baja latencia.',
        provider: 'amazon',
        image: 'https://via.placeholder.com/400x300.png?text=LG+UltraGear',
        price: 319.99,
        rating: 4.6,
        stock: 20,
        available: true,
        url: 'https://amazon.example.com/product/lg-ultragear-27',
        category: 'monitores',
        specs: { refreshRate: '144Hz', resolution: '2560x1440', gSync: true },
      },
      {
        externalId: 'razer-gigantus-v2',
        title: 'Mousepad Razer Gigantus V2',
        description: 'Mousepad de gran tamaño con superficie texturizada.',
        provider: 'mercadolibre',
        image: 'https://via.placeholder.com/400x300.png?text=Razer+Gigantus',
        price: 34.99,
        rating: 4.3,
        stock: 70,
        available: true,
        url: 'https://mercadolibre.example.com/product/razer-gigantus-v2',
        category: 'accesorios',
        specs: { size: 'XL', thickness: '4mm', surface: 'texturizada' },
      },
      {
        externalId: 'logitech-c920',
        title: 'Webcam Logitech C920',
        description: 'Webcam Full HD para streaming y videoconferencias.',
        provider: 'ddtech',
        image: 'https://via.placeholder.com/400x300.png?text=Logitech+C920',
        price: 79.99,
        rating: 4.4,
        stock: 55,
        available: true,
        url: 'https://ddtech.example.com/product/logitech-c920',
        category: 'accesorios',
        specs: { resolution: '1080p', mic: true, autofocus: true },
      },
      {
        externalId: 'thermaltake-850w',
        title: 'Fuente Thermaltake Toughpower 850W',
        description: 'Fuente con certificación 80 Plus Gold y RGB.',
        provider: 'amazon',
        image: 'https://via.placeholder.com/400x300.png?text=Thermaltake+850W',
        price: 139.99,
        rating: 4.5,
        stock: 30,
        available: true,
        url: 'https://amazon.example.com/product/thermaltake-850w',
        category: 'fuentes-poder',
        specs: { wattage: '850W', modular: true, rgb: true },
      },
      {
        externalId: 'cooler-master-nr600',
        title: 'Gabinete Cooler Master NR600',
        description: 'Gabinete con malla frontal y buen flujo de aire.',
        provider: 'mercadolibre',
        image: 'https://via.placeholder.com/400x300.png?text=NR600',
        price: 89.99,
        rating: 4.3,
        stock: 29,
        available: true,
        url: 'https://mercadolibre.example.com/product/cooler-master-nr600',
        category: 'gabinetes',
        specs: { formFactor: 'ATX', fansIncluded: 2, frontMesh: true },
      },
      {
        externalId: 'ryzen-7-7700x',
        title: 'Procesador AMD Ryzen 7 7700X',
        description: 'Procesador de 8 núcleos para gaming y creación de contenido.',
        provider: 'cyberpuerta',
        image: 'https://via.placeholder.com/400x300.png?text=Ryzen+7+7700X',
        price: 259.99,
        originalPrice: 329.99,
        discount: 21,
        rating: 4.7,
        stock: 24,
        available: true,
        url: 'https://cyberpuerta.example.com/product/ryzen-7-7700x',
        category: 'procesadores',
        specs: { cores: 8, threads: 16, baseClock: '4.5GHz', boostClock: '5.4GHz' },
      },
      {
        externalId: 'rtx-4070',
        title: 'Tarjeta de Video RTX 4070',
        description: 'GPU de última generación para gaming en 1440p y más.',
        provider: 'amazon',
        image: 'https://via.placeholder.com/400x300.png?text=RTX+4070',
        price: 599.99,
        rating: 4.6,
        stock: 14,
        available: true,
        url: 'https://amazon.example.com/product/rtx-4070',
        category: 'tarjetas-video',
        specs: { memory: '12GB', type: 'GDDR6X', interface: 'PCIe 4.0' },
      },
      {
        externalId: 'crucial-p3-2tb',
        title: 'SSD Crucial P3 2TB NVMe',
        description: 'Almacenamiento rápido para proyectos grandes.',
        provider: 'mercadolibre',
        image: 'https://via.placeholder.com/400x300.png?text=Crucial+P3',
        price: 149.99,
        rating: 4.5,
        stock: 45,
        available: true,
        url: 'https://mercadolibre.example.com/product/crucial-p3-2tb',
        category: 'almacenamiento',
        specs: { capacity: '2TB', interface: 'NVMe PCIe 3.0', readSpeed: '3500MB/s' },
      },
      {
        externalId: 'razer-blackshark-v2',
        title: 'Headset Razer BlackShark V2',
        description: 'Audífonos para gaming con sonido THX y micrófono profesional.',
        provider: 'ddtech',
        image: 'https://via.placeholder.com/400x300.png?text=BlackShark+V2',
        price: 64.99,
        originalPrice: 99.99,
        discount: 35,
        rating: 4.6,
        stock: 38,
        available: true,
        url: 'https://ddtech.example.com/product/razer-blackshark-v2',
        category: 'audífonos',
        specs: { surround: true, mic: true, weight: '262g' },
      },
    ]);

    console.log('✅ Productos creados:', products.length);

    // Crear usuario admin de ejemplo
    const adminUser = await User.create({
      name: 'Admin',
      email: 'admin@example.com',
      password: 'admin123',
      role: 'admin',
    });

    console.log('✅ Usuario admin creado:', adminUser.email);

    console.log('🎉 Base de datos poblada exitosamente!');
    console.log('📊 Resumen:');
    console.log(`   - ${categories.length} categorías`);
    console.log(`   - ${products.length} productos`);
    console.log(`   - 1 usuario admin`);

  } catch (error) {
    console.error('❌ Error poblando la base de datos:', error.message);
  } finally {
    await mongoose.connection.close();
    console.log('🔌 Conexión a MongoDB cerrada');
  }
}

seedDatabase();